# Generated by Django 4.2.1 on 2023-05-13 11:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUploader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='AllImages')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
